### ISSUE TITLE
Discourage python2 use!

### ISSUE THREAD

**Issue by hcooper** [snipsco/snips-skill-weather-tts#1]
Seeing new python2 code committed in 2018 makes me sad :-(

You may be interested in https://github.com/snipsco/snips-issues/issues/26 - which explains that `hermes-python` works with very little modification in python 3. If the code was still on github I'd be putting a patch up for it.

Maybe with a little pressure we can get `hermes-python` published for python 3! :-)

**Comment by nebuto** [comment]
Updated to python 3
