### ISSUE TITLE
Session closed in case of unknown/unhandled intent

### ISSUE THREAD

**Issue by CrystalMethod** [snipsco/snips-skill-weather-tts#2]
Current implementation closes dialog session in case of unhandled intents. This is troubling, if other skills are installed as well. Their session may already be closed.

https://github.com/snipsco/snips-skill-weather-tts/blob/master/action-weatherIntentTtsParser-weather.py#L11-L25

**Comment by nebuto** [comment]
Fixed in commit ca471aa
